export const skills = [
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "JavaScript: ES6+",
    "Immutability",
    "CSS BEM convention",
    "Github Pull Requests & Review",
    "CSS Grid",
    "CSS Flexbox",
    "React",
    "React Router",
    "React Hooks",
    "Redux-Saga",
    "Redux (Toolkit)",
    "Error handling",
    "Working with API (fetch, axios)",
    "Promises, Async/Await",
    "Teamwork",
    "Markdown",
    "Trello",
    "Scrum",
    "NPM",
    "Git",
];